use_frameworks!

target 'WBasicLibrary_Example' do
  pod 'WBasicLibrary', :path => '../'

  target 'WBasicLibrary_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
